### ISSUE TITLE
Deleted node example?

### ISSUE THREAD

**Issue by billjohnston** [awslabs/aws-support-tools#100]
https://github.com/awslabs/aws-support-tools/commit/c9090246d09dca07aaaca517a3884ccaba3b163e#diff-c84d2b498352c64f27fe8574c914d2a6

I reference this all the time, why was it deleted?

**Comment by joshua-at-aws** [comment]
Hello,

The example was removed to reduce confusion, since the Amazon Cognito Developer Guide added an official Node.js example here using a different library:

https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-verifying-a-jwt.html

By the way, if you would like to publish a reusable serverless application under an approved open source license such as Apache-2.0, you can do so using the AWS Serverless Application Repository

https://docs.aws.amazon.com/serverlessrepo/latest/devguide/serverlessrepo-quick-start.html

Those applications can be both used as a reference and easily deployed directly from https://serverlessrepo.aws.amazon.com/applications
