### ISSUE TITLE
Check against aud should be against client_id?

### ISSUE THREAD

**Issue by craigatproperly** [awslabs/aws-support-tools#33]
It appears to me that the check of claims.aud agains app_client_id should actually be checking claims.client_id.

https://github.com/awslabs/aws-support-tools/blob/master/Cognito/decode-verify-jwt/decode-verify-jwt.js#L60

**Comment by emanuelem** [comment]
Hi Craig,

Thank you for pointing that out. The Audience claim in the ID token is called "aud" while in the Access token is, as you mentioned, called "client_id".

Since I have mentioned the ID token in the README.md, then I wrote the code consequently; however it s probably a good idea to mention this difference in a comment.
